### ISSUE TITLE
List internships that aren't N/A first

### ISSUE THREAD

**Issue by aglucky** [AlanChen4/Summer-2024-SWE-Internships#2]
Happy to help out if you'd like, can't do a Pr without seeing source code though

**Comment by AlanChen4** [comment]
Source code is still a mess but will consider once i get it cleaned up lol

Curious what you mean by "list internships that aren't N/A first" - is this not what the repo currently is? The top of the repo are companies that are already open, followed by companies that are currently being monitored.

Thanks!

**Comment by aglucky** [comment]
Looks like I misread, I saw that JP Morgan was not N/A which made me think it was open.
